name:
  en: Roomle Configurator
  de: Roomle-Konfigurator
icon: roomle
label:
  en: "{{ mainproductid }} · {{ variants.length }} variant(s)"
  de: "{{ mainproductid }} · {{ variants.length }} Variante(n)"
tabs:
  views:
    label:
      en: Views
      de: Ansichten
    fields:
      mainProductId:
        label:
          en: ID of the main view
          de: ID der Hauptansicht
        type: text
        counter: false
        help:
          en: Can be an item, configuration or plan ID (plan ID only in room mode)
          de: Kann eine Produkt-, Konfigurations- oder Plan-ID sein (Plan-ID nur im Raum-Modus)
        icon: box
        required: true
      variants:
        label:
          en: Variants
          de: Varianten
        type: structure
        columns:
          productId:
            mobile: true
          title:
            mobile: true
          subtitle:
          image:
        empty:
          en: No variants yet
          de: Noch keine Varianten
        fields:
          productId:
            label:
              en: ID
              de: ID
            type: text
            icon: box
            counter: false
            required: true
          title:
            label:
              en: Title
              de: Titel
            type: text
            required: true
            width: 1/2
          subtitle:
            label:
              en: Subtitle
              de: Untertitel
            type: text
            width: 1/2
          image:
            label:
              en: Image
              de: Bild
            type: files
            empty:
              en: No custom image yet, uses rendering of the product
              de: Noch kein eigenes Bild, verwendet Rendering des Produkts
            multiple: false
            query: page.images
  Behavior:
    label:
      en: Behavior
      de: Verhalten
    fields:
      mode:
        label:
          en: Configuration mode
          de: Konfigurations-Modus
        type: toggles
        default: product
        options:
          -
            icon: cog
            text:
              en: Product
              de: Produkt
            value: product
          -
            icon: home
            text:
              en: Room (multi-object configurator)
              de: Raum (Multi-Objekt-Konfigurator)
            value: room
        required: true
      initialView:
        label:
          en: Initial view
          de: Initiale Ansicht
        type: toggles
        default: detail
        options:
          -
            text:
              en: Detail view
              de: Detailansicht
            value: detail
          -
            text:
              en: Room/Drawing view
              de: Raumansicht/Zeichenmodus
            value: room
          -
            text:
              en: Catalog view
              de: Katalogansicht
            value: catalog
        required: true
        when:
          mode: room
      useCatalogRootTag:
        label:
          en: Catalog
          de: Katalog
        type: toggles
        default: default
        grow: false
        options:
          -
            text:
              en: Default
              de: Standard
            value: default
          -
            text:
              en: Custom
              de: Eigener
            value: custom
          -
            icon: cancel
            text:
              en: None
              de: Keiner
            value: none
        required: true
        when:
          mode: room
        width: 1/3
      catalogRootTag:
        label:
          en: Custom catalog root tag
          de: Eigener Stamm-Tag für den Katalog
        type: text
        counter: false
        icon: tag
        width: 2/3
        when:
          mode: room
          useCatalogRootTag: custom
  advanced:
    label:
      en: Advanced
      de: Erweitert
    fields:
      info:
        label: false
        type: info
        text:
          en: These settings override the global default settings. Only change them if needed.
          de: Diese Einstellungen haben Vorrang vor den globalen Standard-Einstellungen. Verändere sie nur wenn nötig.
      useConfiguratorId:
        label:
          en: Configurator ID
          de: Konfigurator-ID
        type: toggles
        default: default
        grow: false
        options:
          -
            text:
              en: Default
              de: Standard
            value: default
          -
            text:
              en: Custom
              de: Eigene
            value: custom
        required: true
        width: 1/3
      gap:
        type: gap
        when:
          useConfiguratorId: default
        width: 2/3
      configuratorId:
        label:
          en: Custom configurator ID
          de: Eigene Konfigurator-ID
        type: text
        counter: false
        icon: box
        required: true
        when:
          useConfiguratorId: custom
        width: 2/3
      useTarget:
        label:
          en: Request target page
          de: Anfrage-Zielseite
        type: toggles
        default: default
        grow: false
        options:
          -
            text:
              en: Default
              de: Standard
            value: default
          -
            text:
              en: Custom
              de: Eigene
            value: custom
          -
            icon: cancel
            text:
              en: None
              de: Keine
            value: none
        required: true
        width: 1/3
      target:
        label:
          en: Custom target page
          de: Eigene Zielseite
        type: pages
        empty:
          en: No custom target page yet
          de: Noch keine eigene Zielseite
        multiple: false
        required: true
        when:
          useTarget: custom
        width: 2/3
      options:
        label:
          en: Configurator options
          de: Konfigurator-Optionen
        type: textarea
        buttons: false
        counter: false
        font: monospace
        help:
          en: Overrides for the <a href="https://docs.roomle.com/web/embedding/api/interfaces/types.UiInitData.html">Roomle configurator options</a> in YAML syntax
          de: Ergänzende <a href="https://docs.roomle.com/web/embedding/api/interfaces/types.UiInitData.html">Roomle Konfigurator-Optionen</a> in YAML-Syntax
        size: medium
        spellcheck: false
